global:
  imageRegistry: "public.ecr.aws"

architecture: replicaset
replicaCount: 2
replicaSetName: rs0
useStatefulSet: true

auth:
  enabled: true
  existingSecret: mongo

arbiter:
  enabled: false

metrics:
  enabled: true
  resources:
    requests:
      memory: 100Mi
    limits:
      memory: 200Mi

persistence:
  size: 4Gi

resourcesPreset: xlarge

service:
  nameOverride: ""     # Keep default naming so primary/secondary services are created
  type: NodePort
  port: 27017
  nodePorts:
    mongodb: 32017
