global:
  imageRegistry: public.ecr.aws
  compatibility:
    openshift: false

# ----------------------------
# MongoDB Image (ECR MIRROR)
# ----------------------------
image:
  repository: bitnami/mongodb
  tag: 7.0.11
  pullPolicy: IfNotPresent

# ----------------------------
# Architecture
# ----------------------------
architecture: replicaset
replicaCount: 2
replicaSetName: rs0
useStatefulSet: true

# ----------------------------
# Authentication
# ----------------------------
auth:
  enabled: true
  existingSecret: mongo

# ----------------------------
# Arbiter
# ----------------------------
arbiter:
  enabled: false

# ----------------------------
# Metrics (ECR MIRROR)
# ----------------------------
metrics:
  enabled: true
  image:
    repository: bitnami/mongodb-exporter
    tag: 0.40.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 100Mi
    limits:
      memory: 200Mi

# ----------------------------
# Persistence
# ----------------------------
persistence:
  enabled: true
  size: 1Gi

# ----------------------------
# Resources
# ----------------------------
resourcesPreset: small
